algorithm_config:
  population_size: 1000
  class_name: "archer"
  population_to_keep: 500
  iterations: 1000
  # Limit for the number of iterations without improvement
  same_best_solution: 10
  # Number of decimals to round the best solution
  best_solution_decimals: 1

crossover_config:
  # Options are "uniform", "one_point", "two_point" or "annular"
  type: "uniform"

mutation_config:
  # Mutation rate for each individual or gene
  rate: 0.05
  # Options are "gen" or "multi_gen"
  type: "multi_gen"
  # Delta for the mutation
  delta: 10

selection_config:
  # Options are "elite", "roulette", "universal", "boltzmann", "ranking", "probabilistic_tournament", "deterministic_tournament"
  type: "roulette"
  # Boltzmann temperature
  initial_temperature: 50
  # Boltzmann temperature decay
  temperature_decay: 0.1
  # Boltzmann temperature minimum
  min_temperature: 5
  # Tournament quantity selection
  tournament_size: 50
  # threshold for the probabilistic tournament selection [0.5, 1]
  tournament_threshold: 0.75

replacement_config:
  # Options are "generational", "traditional" or "young_bias"
  type: "generational"
  # Generational gap for the replacement
  gen_gap: 0.2

end_condition_config:
  # Options are "generations", "structure", "content" or "optimum"
  type: "content"
  # Number of generations
  generations: 500
  # Number of generations without improvement (content)
  generations_to_check: 50
  # Optimum value
  optimum: 61.5
  # Tolerance for optimum
  tolerance: 0.1
