show_crossover_performance: False
show_mutation:
  by_type: False
  by_rate: False
  by_delta: False
show_selection:
  tournaments: False
  boltzmann: False
show_algorithm:
  by_population_size: False
  by_population_to_keep: True
