use_default: False
class_names: ["warrior", "archer", "defender", "assasin"]
repetitions: 1
param_to_change_group: "algorithm_config"
param_to_change_name: "population_to_keep"
param_value:
  # True if the parameter is numeric, False if it is categorical
  numeric: True
  numeric_value:
    min_value: 0.1
    max_value: 0.9
    step: 0.1
  categorical_values: ["uniform", "one_point", "two_point","annular"]
