use_default: False
class_names: ["warrior"]
repetitions: 5
params_to_change:
  # tournaments
  # - param_to_change_group: "selection_config"
  #   param_to_change_name: "type_1"
  #   param_value:
  #     numeric: False
  #     categorical_values: ["probabilistic_tournament", "deterministic_tournament"]
  # - param_to_change_group: "selection_config"
  #   param_to_change_name: "ratio_A"
  #   param_value:
  #     numeric: True
  #     numeric_value:
  #       min_value: 1
  #       max_value: 1
  #       step: 1
  # - param_to_change_group: "selection_config"
  #   param_to_change_name: "tournament_threshold"
  #   param_value:
  #     numeric: True
  #     numeric_value:
  #       min_value: 0.5
  #       max_value: 1
  #       step: 0.1
  # - param_to_change_group: "selection_config"
  #   param_to_change_name: "tournament_size"
  #   param_value:
  #     numeric: True
  #     numeric_value:
  #       min_value: 20
  #       max_value: 100
  #       step: 20
  




  # boltzmann
  - param_to_change_group: "selection_config"
    param_to_change_name: "type_1"
    param_value:
      numeric: False
      categorical_values: ["boltzmann"]
  - param_to_change_group: "selection_config"
    param_to_change_name: "ratio_A"
    param_value:
      numeric: True
      numeric_value:
        min_value: 1
        max_value: 1
        step: 1
  - param_to_change_group: "selection_config"
    param_to_change_name: "initial_temperature"
    param_value:
      numeric: True
      numeric_value:
        min_value: 10
        max_value: 50
        step: 10
  - param_to_change_group: "selection_config"
    param_to_change_name: "temperature_decay"
    param_value:
      numeric: True
      numeric_value:
        min_value: 0.1
        max_value: 1
        step: 0.2
  - param_to_change_group: "selection_config"
    param_to_change_name: "min_temperature"
    param_value:
      numeric: True
      numeric_value:
        min_value: 2
        max_value: 10
        step: 2
